[project]
name = "imageorganizer"
version = "2.0.0"
description = "Organize images by camera Make/Model."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "ruff>=0.12.7",
    "tqdm>=4.67.1",
]
